# Generated by Django 4.2 on 2023-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimaond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Z', models.FloatField()),
                ('carat', models.FloatField()),
                ('depth', models.FloatField()),
                ('table', models.FloatField()),
                ('price', models.FloatField()),
                ('cut', models.FloatField()),
                ('color', models.FloatField()),
                ('clarity', models.FloatField()),
            ],
        ),
    ]
