# Generated by Django 4.2 on 2023-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaond',
            name='price',
        ),
        migrations.AddField(
            model_name='dimaond',
            name='price1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dimaond',
            name='price2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dimaond',
            name='price3',
            field=models.FloatField(default=0.0),
        ),
    ]
